# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" "rtsx_usb_sdmmc" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/944ad7b7-9848-48f6-b0bf-516365a0af4a";
      fsType = "ext4";
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/ecb14a26-c4c6-4741-8f8e-df8659f97a54";
      fsType = "ext4";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/24f18a31-4f87-4012-a47c-41172f14364f"; }
    ];

  nix.maxJobs = lib.mkDefault 4;
}
